### ISSUE TITLE
tue-get improvements

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#113]
## tue-get general
- [ ] Change output of package.xml and install.yaml parsers, so it can be used for removal too.

## tue-get update
- [ ] Seperate gathering of targets and execution completely

## tue-get remove
- [ ] 1. Check if remaining targets depend on the targets which are going to be removed. Then only removal from installed list is needed.
- [ ] 2. Removal procedures
  - [ ] System: sudo apt-get remove target. Issue: Maybe other installed system targets depend on this one
  - [ ] Pip: equal to system 
  - [ ] Git: Check if repo is used by other packages, otherwise only delete symbolic link.

## tue-get autoremove
- [ ] Check if 'depend on' list is empty or not present. 'Depend on list is updated during tue-get update'

**Comment by Rayman** [comment]
Simpler solution for autoremove and remove:
```
rm .env/installed/thingy && cd trunk && rm * && tue-get update
```
