### ISSUE TITLE
Clean up dashboard targets

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue-env#12]
Currently, we have the following dash targets:
ros-amigo_dashboard
ros-dashboard
ros-pr2_dashboard
ros-rqt_amigo_dashboard
ros-rqt_robot_dashboard
ros-tue_dashboard
Are they all necessary? Shouldn't this be cleaned up?

**Comment by Rayman** [comment]
All the bold packages can be deleted as far as I know.

- **rqt_amigo_dashboard** (hvos) I don't know
- **rqt_robot_dashboard**, empty
- **amigo_dashboard**, this is the old tue_dashboard
- **tue_dashboard**, obsolete rxtools
- pr2_dashboard, just a package you can depend on
- dashboard, the new dashboard
