### ISSUE TITLE
running orocos components from dev build folder

### ISSUE THREAD

**Issue by robinsoetens** [tue-robotics/tue-env#13]
Suppose for instance 'rtt_control_components' has been installed in the trunk and build from there. After pulling this package to the dev space, and building it there, orocos by default still loads the modules that were compiled from the trunk (the ones in system/devel or system/build). One would expect the orocos modules in the dev build folder are getting higher priority than the ones from the trunk, as with other packages.

**Comment by Timple** [comment]
I fix this by removing the build/lib/orocos/rtt_control_components directory from the /system/

Maybe a better proposal is that when packages are put to dev, their symlink is also removed from "trunk".

**Comment by Timple** [comment]
Alternative:

Find how orocos finds the components, implement a check for a double component and keep only the first found (path order).
Then pullrequest this to orocos and hope they agree on a more ROS-like feeling for orocos-component-searching
