### ISSUE TITLE
Slow sourcing of target

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#132]
It is caused by sourcing setup.bash in the dev space. That setup file sources setup.sh. Which is linked to ```/home/amigo/ros/kinetic/dev/devel/.private/catkin_tools_prebuild/setup.sh```

The lines which are the real problem are the following:
```
# source all environment hooks
_i=0
while [ $_i -lt $_CATKIN_ENVIRONMENT_HOOKS_COUNT ]; do
  eval _envfile=\$_CATKIN_ENVIRONMENT_HOOKS_$_i
  unset _CATKIN_ENVIRONMENT_HOOKS_$_i
  eval _envfile_workspace=\$_CATKIN_ENVIRONMENT_HOOKS_${_i}_WORKSPACE
  unset _CATKIN_ENVIRONMENT_HOOKS_${_i}_WORKSPACE
  # set workspace for environment hook
  CATKIN_ENV_HOOK_WORKSPACE=$_envfile_workspace
  . "$_envfile"
  unset CATKIN_ENV_HOOK_WORKSPACE
  _i=$((_i + 1))
done
```
These are all auto-generated files, so probably there is no direct solution

**Comment by Rayman** [comment]
These are generated by catkin hooks, we can't do anything about it
