### ISSUE TITLE
Travis builds fail with bootstrap

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue-env#14]
Pleas see https://travis-ci.org/tue-robotics/robot_smach_states

    [tue] Environment directory '/home/travis/ros/hydro' (environment 'hydro') does not exist
    The command "source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap)" failed and exited with 1 during .

**Comment by Timple** [comment]
Same issue when trying to install indigo.

Manually creating the directory is a workaround.

**Comment by Rayman** [comment]
Fixed by bfdf19dd8aa4864c1f8765a9e9a6feba1bb7955d
