### ISSUE TITLE
Why do the ros tutorials get installed???

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue-env#15]

**Comment by Rayman** [comment]
`rosbridge_library` depends on `rospy_tutorials`

**Comment by LoyVanBeek** [comment]
Can we check whether they are actually needed an strip them out in a pull request?

**Comment by svddries** [comment]
Just checked. Apparently it uses messages from the ROS tutorials in its test. *Sigh*...

**Comment by Rayman** [comment]
Will be fixed by tue-robotics/rosbridge_suite@91b6b439689f2d9f0726a0e8de0c0e1ddc897a90
