### ISSUE TITLE
CI bug, dependencies in PR/branch/commit not installed

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#185]
If dependencies are updated in a PR/branch/commit, these are not installed. This caused by first installing the package based on the package.xml in the default branch. Then the package is checked out to the correct branch. So new dependencies in the package.xml are not installed.

**Comment by ar13pit** [comment]
@MatthijsBurgh is this still a problem?

**Comment by MatthijsBurgh** [comment]
yes

**Comment by ar13pit** [comment]
@MatthijsBurgh Did we solve this in #505 ?

**Comment by MatthijsBurgh** [comment]
Yes this it solved.
