### ISSUE TITLE
Trying to set up a tue-dev:tng (the next generation)

### ISSUE THREAD

**Issue by alberth** [tue-robotics/tue-env#19]
Ideas and description in /doc, other changes in this branch can be largely ignored.

Current goals are to handle all that we need in an as simple as possible setup, have no sourced shell scripts (since they fail if you change login shell), and no environment variable magic exposed in user space (so you don't need to remember setup etc).

See the tueenv_tng branch
Feedback welcome

**Comment by Rayman** [comment]
Looks good! Here are a few idea's that I have for the new system:

If a package needs to modify the (bash) environment, for example to load tab completion scripts, you can use [`catkin_add_env_hooks`](http://docs.ros.org/jade/api/catkin/html/dev_guide/generated_cmake_api.html) from the `CMakeLists.txt`. We now do this with our `setup` files defined in the `tue-env` package but I think that the ROS way is more clean.

Native support for `pip` dependencies. We now use custom bash scripts for that ([ros-python-scipy](https://github.com/tue-robotics/tue-env/blob/7c93744ae71ce5e804f55dffcaac9c3227f63f09/installer/targets/ros-python-scipy/install.bash)) but that is ugly. Maybe create a [virtualenv](https://virtualenv.pypa.io/en/latest/index.html) for each workspace?

**Comment by alberth** [comment]
Updated the https://github.com/tue-robotics/tue-env/tree/tueenv_tng/doc/devmgr documentation, with some fleshing out of the module meta information (dependencies/how to build/download/etc).

@Rayman I am trying to make it a little bit more generic even; I don't want to connect hard with ROS, as in, you should also be able to use it in non-ROS environments, possibly by extending things a bit. That way it won't die if we ever move away from ROS, or if the Turtle team wants to use this too.

I very very very much hate having environment variables in my shell that need to be setup properly. That will definitely get solved one way or another.

I haven't yet looked into details of setup, but I will look into your suggestions when I get there.

**Comment by Rayman** [comment]
This is a related project: https://github.com/robotology-playground/robotology-superbuild

**Comment by alberth** [comment]
Thanks for the link.

Yeah, likely there are lots of these tools. However they tend to

1. Assume hard-coded use of .bashrc, which breaks completely if you use a different shell, like zsh (which I do, so tue-env simply doesn't work at all for me).
2. Totally rely on use of environment variables which breaks if you have more than one setup that you work in. Can't have different setups both in .bashrc. You hack around the problem by adding random environment set scripts that you have to source rather than run. That in turn ties your shell session to an environment, which means you can't just cd to a different place and start working there.

I believe the only way out is to move all environment variables crap to the commands that you run, like a wrapper that adds environment variable settings around each command that you run, but dynamic, based on the directory where you perform the command.
