### ISSUE TITLE
Any reason not to go back to kinetic release of rosbridge?

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue-env#200]
Why do we have our source version @Rayman

**Comment by Rayman** [comment]
I have tested this once, but that was not successful. It might have been an issue with the workspace though. Let's try it again.

**Comment by MatthijsBurgh** [comment]
New GUI doesn't work with upstream from source. General layout is there, but seems that all communication to ROS is not working. Because teleop isn't working, no cameraview, not loading arm configuration etc.

**Comment by reinzor** [comment]
Better figure this out instead of depending on forked code :)

**Comment by MatthijsBurgh** [comment]
Indeed, but might be a pain in the ass.

**Comment by MatthijsBurgh** [comment]
I tested with the original repo. The problem is that older version contained a fork of tornado. This is remove in 0.9.0. So you need to clean your workspace to get it working. But apart from that, no issues.

Do we prefer to use the original repo or the kinetic release?

**Comment by MatthijsBurgh** [comment]
@reinzor original repo or released debian? What do you think?

**Comment by MatthijsBurgh** [comment]
Debian it is.
