### ISSUE TITLE
pycharm ppa out of date

### ISSUE THREAD

**Issue by Timple** [tue-robotics/tue-env#206]
mystic ppa is outdated see 
http://ubuntuhandbook.org/index.php/2016/07/latest-pycharm-ubuntu-16-04-ppa/

New method found here:
http://ubuntuhandbook.org/index.php/2016/12/pycharm-2016-3-1-released-install-it-via-getdeb-repository/

**Comment by MatthijsBurgh** [comment]
The new one is working, but no up-to-date. Maybe we could use some code from https://github.com/baderas/package-jetbrains-ide/tree/master/data/pycharm

**Comment by MatthijsBurgh** [comment]
It is also possible to use snap: ```sudo snap install [pycharm-professional|pycharm-community] --classic```. I didn't know anything of snap before founding this out. So feedback please.
