### ISSUE TITLE
git config user.name and user.email being reset

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#246]
With every reboot, my `~/.gitconfig` file is being restored to default, thus resetting user.name and user.email.

When I commented out `source ~/.tue/setup.bash` in `~/.bashrc` this problem doesn't occur.

I know the workaround is setting the user.name and user.email in `~/.bashrc`, but is there a way for `setup.bash` to not mess this up?

**Comment by Rayman** [comment]
That's not supposed to happen, I'll take a look at it next tuesday

**Comment by MatthijsBurgh** [comment]
I have never seen this happen. Maybe you could reduce the permissions of the user/group to the file. Then you will probably get an error somewhere, which will be the cause of the problem.

**Comment by MatthijsBurgh** [comment]
Status?

**Comment by Rayman** [comment]
I can't find any code that does anything with `.gitconfig`:
https://github.com/search?q=org%3Atue-robotics+.gitconfig&type=Code
