### ISSUE TITLE
[ros-robot_api] Does not contain a valid ROS package.xml.

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#26]

**Comment by Rayman** [comment]
This is by design. Its a NodeJS module.

**Comment by Rayman** [comment]
The target should be removed, good point

**Comment by alberth** [comment]
Perhaps add a comment why it's not there, as it obviously causes confusion.

**Comment by LoyVanBeek** [comment]
Would stating a different type solve things as well?

**Comment by Rayman** [comment]
It is not a ROS package. You can't install it with tue-env. My opinion is that it does not belong in tue-env.

**Comment by LoyVanBeek** [comment]
But pycharm and sublime are in there as well. And it's part of the tue-env-ironment.
