### ISSUE TITLE
"quickssh" command can overwrite any existing ssh config file

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#285]
[quickssh](https://github.com/tue-robotics/tue-env/blob/master/installer/targets/robot-user/setup) alias on the last lines of the file has a potential to overwrite any existing ssh config files.

Also, are we ever using this alias in practice? As using ControlMaster has some caveats that the user must be aware of.

**Comment by MatthijsBurgh** [comment]
@ar13pit I don't know anything about it. Contact @Timple to get more information about it.

**Comment by ar13pit** [comment]
@Timple is it okay to remove the [quickssh](https://github.com/tue-robotics/tue-env/blob/master/installer/targets/robot-user/setup) alias?

**Comment by Timple** [comment]
Can be removed!

**Comment by ar13pit** [comment]
[#286](https://github.com/tue-robotics/tue-env/pull/286) closes this.
