### ISSUE TITLE
Upgrade to Melodic Morenia

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#297]
It has been 6 months since the release of Ubuntu 18.04 and ROS Melodic. CUDA for Ubuntu 18.04 too has been released and OpenCV 4.0.0 was released a couple of days back.

Is it a good time to think about an upgrade?

**Comment by Timple** [comment]
I fixed the installer already a while ago:
https://github.com/tue-robotics/tue-env/compare/melodic

**Comment by MatthijsBurgh** [comment]
We need to wait, till Toyota switches...

**Comment by MatthijsBurgh** [comment]
PR is merged, so closing this issue. Because we need to wait because of Toyota.
