### ISSUE TITLE
Remove as much pip targets as possible

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue-env#30]

**Comment by MatthijsBurgh** [comment]
Installer can accept pip targets now, so all bash scripts with pip targets should be transfered to yaml. It is still on a [pip branch](/github/tue-robotics/tue-env/pip). I haven't been able to test it.

**Comment by Timple** [comment]
What happens if a switch to apt-get is performed in this branch but people already have the pip version installed?

**Comment by LoyVanBeek** [comment]
https://askubuntu.com/questions/431780/apt-get-install-vs-pip-install 
As noted there, mixing apt-get and pip may cause inconsistencies and I have seen it happen.

**Comment by MatthijsBurgh** [comment]
I am only converting the pip bash scripts to pip yaml. I am not converting pip to apt-get or vice-versa. But switching seems tricky,

**Comment by Timple** [comment]
We can do it ugly: A) uninstall the pip. 
Or nicer: B) check for conflicts within the apt-get function and the pip function. 
But in both cases we need the name, are they always the same for apt and pip? Probably not. 

Alternative, C) for all targets currently existsing, put a install.yaml but also a install.bash which checks pip installation and if there offers an uninstall. 

After a transition period the install.bash can be removed 

Or D) just convert to apt and hope no conflicts will occur, chance seems small anyway. 

Other thoughts?

**Comment by MatthijsBurgh** [comment]
I don't now how you could check for conflicts. In case of conflicts, which version do you want? Is this package depended?

I am not 100% sure, but I think the name is nearly the same. apt-get name is python-$pipname.

But first we should decided if we can switch one of the two. Which I think is preferabele.

**Comment by Timple** [comment]
Is there a reason we do a `sudo pip install` instead of an `pip install --user`

No reason to install stuff for all users I guess. It also possibly prevents users having to type their password.

**Comment by LoyVanBeek** [comment]
AFAIK, there is no reason, it's simply easier and the way it's done by default by any tutorial online. 
But no well-considered reason

**Comment by MatthijsBurgh** [comment]
Just like @LoyVanBeek said, I follow our bash scripts. So you blame an other team member. :p

**Comment by Rayman** [comment]
Fixed by #145
