### ISSUE TITLE
Is it a PIP target or a SYSTEM target or both?

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#33]
Which targets should be installed?
https://github.com/tue-robotics/tue-env/tree/master/installer/targets/ros-python-scipy

**Comment by LoyVanBeek** [comment]
I don't know. But most of the time, the pip-version is more recent and up to date, so I'd pick the PIP version then.

**Comment by MatthijsBurgh** [comment]
Ok, I will change this in the [pip branch](/github/tue-robotics/tue-env/pip)

**Comment by Rayman** [comment]
In my opinion one should always prefer system installation (apt-get) because that is faster and more easy to remove. PIP uninstallation is very hard (no autoremove for example). 

PIP is more up-to-date, so in certain cases its the only option.

**Comment by Timple** [comment]
I'd say use apt-get if posseble, but only use pip if a new feature is actually required.

**Comment by MatthijsBurgh** [comment]
So not all python system targets should be transformed tot pip targets, I will transform all bash scripts to yaml, but not transform system targets to pip targets.

**Comment by LoyVanBeek** [comment]
Yes, PIP when we have to, but apt-get if possible.
