### ISSUE TITLE
Openface target

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#34]
https://github.com/tue-robotics/tue-env/tree/master/installer/targets/openface
Is this target used on the robot or only for development? Because I don't think the installer reaches this target. But the python packages, numpy and pandas, seem te be used in multiple parts of our system, but aren't installed by other targets.

**Comment by reinzor** [comment]
Only if you want to install openface ros. We install this manually since not everybody wants to use openface.

**Comment by MatthijsBurgh** [comment]
And how about numpy? Should this be included in an other target? Because it isn't at the moment, but it is used in multiple parts of the system.

**Comment by reinzor** [comment]
Packages should specify their own deps, so this should be resolved in those
specific packages.

-Rein

**Comment by MatthijsBurgh** [comment]
I agree!
