### ISSUE TITLE
Fix numpy depencies

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#35]

**Comment by MatthijsBurgh** [comment]
fixed by
tue-robotics/tue_robocup#155
tue-robotics/image_recognition#7

**Comment by reinzor** [comment]
image recognition is merged

**Comment by Rayman** [comment]
See this PR tue-robotics/tue_robocup#155

**Comment by MatthijsBurgh** [comment]
Both PR merged
