### ISSUE TITLE
Correct version of targets in CI

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#356]
At the moment, the targets are not checked out to any branch. Something is implemented, but this is not working correctly.

**Comment by ar13pit** [comment]
To my knowledge there is no target installation in CI at all. All we do is build the ROS package instead of doing `tue-get install` before the build and test

**Comment by MatthijsBurgh** [comment]
We do use `tue-get` in CI, but we don't check out the correct version of the targets list. Something is going wrong there.

**Comment by ar13pit** [comment]
Yes you are right about using `tue-get`. But what do you mean that correct targets list is not being checked out?

**Comment by MatthijsBurgh** [comment]
In CI we checkout all repo's on the same branch if available. We already do this with `tue-env`, because we pull a different docker image. But the targets repo is still on master.

I had a test ci runned in which I printed the branch, it was indeed on `master`, while it should be at `feature/hero-dev`.
Another sign of the issue is https://travis-ci.org/tue-robotics/hero_bringup/builds/488288725#L539. This the `grep` in https://github.com/tue-robotics/tue-env/blob/master/installer/tue-install.bash#L66

**Comment by ar13pit** [comment]
Shouldn't this take care of the right installation (https://github.com/tue-robotics/tue-env/blob/master/installer/tue-install-impl.bash#L236)? I see that the branch flag is being called in the CI as `feature/hero-dev`

**Comment by MatthijsBurgh** [comment]
Yep the repo's are checked out to the correct version. But the target repo, so `tue-env-targets`, is not. That is in `tue-install.bash`

**Comment by ar13pit** [comment]
My PR didn't resolve it
