### ISSUE TITLE
Timeit function

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#365]
We should have a time it function called `tue-timeit` in `tue-functions.bash` as we always need to check the robustness and time execution of our bash scripts.

**Comment by MatthijsBurgh** [comment]
Not sure about it.

**Comment by Timple** [comment]
What would the function do more than
`time tue-get update` for example?

**Comment by ar13pit** [comment]
Nothing more but just make it as a small wrapper for timing a for loop over 100 times and executing something like `tue-get update` inside the loop.

**Comment by MatthijsBurgh** [comment]
We should keep it clean. We don't need development tools in tue-env

**Comment by Timple** [comment]
For future reference:
`python3 -m timeit -s 'import subprocess' 'subprocess.call(["bash", "-c", "tue-get install ros"])'`
