### ISSUE TITLE
Add Docker to YAML?

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#373]
If I am not wrong, we have some software from Toyota that runs on the docker containers. I too am moving the implementation of Kaldi speech recognition to Docker so thought may be it is a good idea to have docker as a part of `install.yaml`.

What are your thoughts on this @MatthijsBurgh @Timple?

**Comment by Timple** [comment]
Suits me, I don't have a preference here

**Comment by ar13pit** [comment]
Closing this as we don't have a use case that needs this yet.
