### ISSUE TITLE
build-docker-image doesn't stop on error

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#393]
Doesn't stop when failing to download apt packages. See https://travis-ci.com/tue-robotics/tue-env/jobs/193292094#L543

**Comment by ar13pit** [comment]
This is not a bug of build-docker-image rather of tue-install-impl.bash because the command calling that particular line is `tue-install-system-now`

**Comment by ar13pit** [comment]
Also I don't understand how did this error pop up because in the existing master builds this was never seen

**Comment by MatthijsBurgh** [comment]
shellcheck...
We use the splitting of the variable. Most of the times, this is unwanted. Therefore shellcheck recommends to change it. I did, but it broke CI. This is all still in a branch. And I was testing it. But this should error the build.

In all the CI scripts we set `exit on error`. But the script calls a dockerfile and the you loose the `exit on error`.

**Comment by ar13pit** [comment]
This is not a docker problem and neither a problem of any of the CI scripts.
See this line https://github.com/tue-robotics/tue-env/blob/master/Dockerfile#L57

If this fails then docker build will exit and in turn the CI script `build-docker-image.bash`. However it does not fail so the check needs to be in tue-install-impl

**Comment by ar13pit** [comment]
@MatthijsBurgh can this issue be closed? Or is this still a problem?

**Comment by MatthijsBurgh** [comment]
I don’t know why I said this was still an issue. APT and other errors are now catched and cause the installer to throw an error. So docker should stop.
