### ISSUE TITLE
Look into the use of Azure pipelines

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#416]
Azure pipelines provides 10 parallel runners for open-source projects. Also it supports dynamic matrix creation.

**Comment by MatthijsBurgh** [comment]
Dynamic matrix creation: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-configuration

**Comment by Rayman** [comment]
Or [github actions](https://github.com/features/actions) when it is released. Github actions will offer a very good integration but I couldn't find anything about the amount of runners.

**Comment by MatthijsBurgh** [comment]
> Or [github actions](https://github.com/features/actions) when it is released. Github actions will offer a very good integration but I couldn't find anything about the amount of runners.

https://help.github.com/en/articles/about-github-actions#usage-limits Mentions 20 workflows and 20 jobs per repo. I don't know if this the technical maximum or the maximum of the default plans.

**Comment by MatthijsBurgh** [comment]
Github Actions should be release on 13th of November https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by MatthijsBurgh** [comment]
Fixed
