### ISSUE TITLE
ROS 2 support

### ISSUE THREAD

**Issue by ruudvd** [tue-robotics/tue-env#432]
Are there plans for supporting ROS 2 in the future?

**Comment by LarsJanssenTUe** [comment]
No concrete plans yet, especially since we are still running python 2.7 on Ubuntu 16.04 So there is a lot of work that has to be done before we even start looking into ROS 2. @MatthijsBurgh any other thoughts?

**Comment by MatthijsBurgh** [comment]
We will not be using ROS 2 ourselves any time soon. Therefore there are no plans yet.

Of course supporting ROS 2 would require many design choices. Drop support for ROS 1? Let ROS 1 and ROS 2 co-exist? This would require support for both `catkin` and `ament`. If you have any suggestions for the design choices, you are welcome to contribute. This means you are also free to open a PR.

**Comment by Rayman** [comment]
The fact that the software runs on the HSR makes this more complicated. We have to wait for support from toyota right?

I think the actionplan is as follows:
1. Go to 18.04 @ melodic (still no melodic from toyota?)
2. Go to 20.04 @ noetic with python3
3. Go to ROS2

**Comment by Timple** [comment]
Can docker be run on the HSR? Then alternatives might be available

**Comment by reinzor** [comment]
> Can docker be run on the HSR? Then alternatives might be available

I think this would not be a problem.

**Comment by reinzor** [comment]
Also what already can be a start is migrating to `colcon build` and `ros1 ros2 bridge`. This way we can build and use `ros1/ros2` packages simultaneously.

**Comment by ruudvd** [comment]
We are investigating what the best option is for us, for now 16.04 is our main OS. But the dropping Python2.7 support beginning next year we are migrating to 18.04 and starting to read into and experimenting with ROS2 and ROS1 bridge

We also face the backwards compatibility, the `ament` could also be a extension of the `catkin_make` to `catkin build` options.

**Comment by Rayman** [comment]
@ruudvd colcon is a new build tool that can build packages of multiple build systems (python, cmake, ament_cmake, ament_python, catkin...). Would this help you for backwards compatibility?

Summary I found on the internet of all the build tools & build systems:

> The build system used for ROS 1 is catkin.
> The build systems used for ROS 2 are ament_cmake and ament_python.
> catkin_make and catkin_tools are build tools that were used for ROS 1 packages.

**Comment by Timple** [comment]
I've played around with colcon for a while.

Didn't like it as much as catkin because

- it did not have colors
- it cannot be run from subfolders of your workspace

Of course the latter one can be worked-around with tue-make

But it does work for just compiling your workspace. If there is serious interest here I can backport these changes I guess

**Comment by LoyVanBeek** [comment]
@Timple Adding colors would be a much welc0omed PR I guess :-). There is also `grc` as a workaround perhaps.

**Comment by ruudvd** [comment]
> @ruudvd colcon is a new build tool that can build packages of multiple build systems (python, cmake, ament_cmake, ament_python, catkin...). Would this help you for backwards compatibility?
> 
> Summary I found on the internet of all the build tools & build systems:
> 
> > The build system used for ROS 1 is catkin.
> > The build systems used for ROS 2 are ament_cmake and ament_python.
> > catkin_make and catkin_tools are build tools that were used for ROS 1 packages.

It could help, we are looking into different options:
- tno-env2 development  for ROS2 and *-env for ROS1
- vcstool with rosdep
- make *-env ROS2 compatible 
- submodules with python/bash script
- ros-get

ros-get is a more generic naming though (we rename tue -> tno), a definable prefix would be nice (or generic like ros-get).

**Comment by LoyVanBeek** [comment]
@ruudvd : ros-get is https://github.com/Rayman/ros-get

**Comment by ruudvd** [comment]
> @ruudvd : ros-get is https://github.com/Rayman/ros-get

I know, that is the fifth option i mentioned. 

> ros-get is a more generic naming though (we rename tue -> tno), a definable prefix would be nice (or generic like ros-get).

This is a example that ros-get command is more generic naming then tue-get
