### ISSUE TITLE
tue-install-cp: copying to non existing location not robust

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#439]
If (a) file(s) is copied to a new location and the destination folder is provided, so not the destination file name. The check if the destination is a directory will return false. This causes it to switch to destination file mode.
i.e.:
```
tue-install-cp blaat.txt /tmp/new_folder
/tmp/new_folder == blaat.txt
/tmp/new_folder/blaat.txt --> doesn't exist
```

**Comment by Timple** [comment]
Isn't this identical to 'standars' copy command?

**Comment by MatthijsBurgh** [comment]
> Isn't this identical to 'standard' copy command?

True, so it is the correct behaviour
