### ISSUE TITLE
CI, should we test against target branch?

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#496]
We were testing against the target branch in the `Pull Request` of travis. But since https://github.com/tue-robotics/tue-env/commit/c11955714c8ebe9d5c765a55c6200fa34ff00d30 we don't test against the target branch anymore. This changed has NOT been applied to all repo's so we don't have a consistent CI behaviour right now.

**Comment by ar13pit** [comment]
So config files of the repo is an issue then? I remember you made changes in the .travis.yml file all repos sometime back. Which repos are facing this issue?

**Comment by MatthijsBurgh** [comment]
The commit is already from 2018, but I know it hasn't been applied to `ed`, I don't know about the all the other repos.

But first we should decided if we want to test the target branch or not?

**Comment by ar13pit** [comment]
Actually we should be testing against both. Because when dependencies change or build process changes, the testing of PR branch will say that the feature/fix/refactor is not gibberish. If that succeeds, then test whether after merge to target branch all tests pass.

So I think we need to add another stage to CI.

**Comment by MatthijsBurgh** [comment]
So right now the repo being tested is checked out to state which represent state after merge. But all other repos are checked out to the source branch of the PR not the target branch.  If we want that, we should revert the commit mentioned above.

**Comment by ar13pit** [comment]
Just to understand you better, you mean with the current commit no repo will be tested in a state after merge and if we revert it back then the repo will be tested against the source branch of the PR and state after merge to target branch as well?

**Comment by MatthijsBurgh** [comment]
With the current state, the repo is always being tested in a commit after merge. But instead of the other repo's being tested on the target branch, master probably. These repos are tested in the source branch, the feature branch or whatever.

**Comment by ar13pit** [comment]
Example case: ED and RGBD have a refactor branch. Default branches of ED and RGBD are `master` and `master` respectively. The CI of ED is running and its `refactor` branch is being merged to `kinetic` (this will be `master` in case the PR is being merged to the default branch).

Conclusions:

1. Branch test: The repo must be tested against the said branch and all the dependent repos must be checked out to the said branch if it exists. In this case, ED will be checked out to `refactor` and all other dependent repos like RGBD will also be checked out to `refactor` if the branch exists in them.

2. PR test: The repo must be brought to a state after merge to target branch and all dependent repos should be checked out to their default branches. In this case, ED will be checked out to a state where `refactor` has been merged to `kinetic` and its dependencies like RGBD are all checked out their default branches like `master`.

**Comment by MatthijsBurgh** [comment]
Ways to implement:
We should checkout pulls/#PR/merge not head on https://github.com/tue-robotics/tue-env/blob/7bb37507ad35513472b53d0ef217aae578ccc053/ci/install-package.sh#L144

I think it should already be checked to the merge branch during the installer, to make sure that any dependencies added on the feature or the target branch are installed. Which is still an issue, #185.
The following fetch line allows for the pull branches to be pulled from GitHub:
```
+refs/pull/*:refs/remotes/origin/pr/*
```
It would be best to not checkout the branch but the hash of it, so that other repos don't have any chance of being checked out, while they shouldn't. (This depends on how we integrate the fetch of the pull branches, if this only happens in the repo of which the CI is run, than the branch name is still oke, in case all repos have their pull branches fetch, the hash is the only option.)

**Comment by ar13pit** [comment]
As a related issue, I think we should split the CI config to two stages. One for the branch test and one for the PR test using conditionals. I have faced this issue on GitLab and it was extremely difficult to figure out what was breaking the CI.

**Comment by MatthijsBurgh** [comment]
I am not sure

**Comment by ar13pit** [comment]
Fixed in #505
