### ISSUE TITLE
Should we copy ip adresses of all pc's to /etc/hosts during install?

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#53]

**Comment by Timple** [comment]
No, the IP adresses of all pcs are changing to often for this to be maintainable.

If hostnames are not being resolved, it might make more sense to troubleshoot this and get it to work I think.

**Comment by MatthijsBurgh** [comment]
1. Even the ip adresses of AMIGO and SERGIO are not even copied.

2. All athome laptops do have a static ip.

**Comment by Timple** [comment]
Then those can be added I guess. I read all PC's. Not all dev-PC's :P

**Comment by reinzor** [comment]
I've added the ROS_IP configuration for all DHCP addresses: 780969bc4a970aad558f4b33c92514e5f96ab609 

Robot IP's seems good to me

**Comment by LoyVanBeek** [comment]
Instead of adding everything to /etc/hosts, can't we run a DNS on our router?

**Comment by reinzor** [comment]
Yes, and that is already running. The only reason we want the /etc/hosts
file is for when the connection to the router's DNS server is lost.
Therefore, it is only required for the robot PC's

-Rein

**Comment by LoyVanBeek** [comment]
That makes sense indeed. And then only for robot-PC to robot-PC?

**Comment by Timple** [comment]
Yes, that is what I meant! :-)

We should look into that. Then only the Amigo PC's need to be in the hosts
file. Because there might not always be a router connected to Amigo. But if
developers PC's are connected there is always a router present

Op 20 feb. 2017 8:45 a.m. schreef "Loy" <notifications@github.com>:

**Comment by Timple** [comment]
Closed? So the hosts files  with the robot PCs are now automatically copied to the robot PCs?

**Comment by MatthijsBurgh** [comment]
No, I wass not expecting it to happen anymore. So we are going to copy all ip's of robot and dev pc's to all dev pc's and only robot pc's to the other robot pc's?

**Comment by Timple** [comment]
No, as I understand. We copy only the robot ips to the robots.

**Comment by MatthijsBurgh** [comment]
Why only that option? Because on the GO, Max did send a list of all pc's to put in the hosts file.

**Comment by MatthijsBurgh** [comment]
Question, not about which IP adresses, but how to do it. You want the installer to copy it every time, because the IP adresses can change over time. This is already solved by tue-install-cp.

Main problem, it needs sudo. Which is unwanted, because we don't want to enter our password every time we run tue-get update.

**Comment by Timple** [comment]
Look at the solution I implemented in installer/targets/amigo1/install.bash

First I perform a cmp before sudo is required.

>

**Comment by Timple** [comment]
Regarding the IPs. all hosts is also fine,

**Comment by Rayman** [comment]
We could connect to the HSR without configuration `ssh hsrb.local`. How does that work?

**Comment by reinzor** [comment]
Router dns 

-Rein
