### ISSUE TITLE
private repos in bootstrapper

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue-env#549]
During installation of a new environment. I ran into trouble with the hsr-setup. It tried to install the private repository and failed to because the system was unknown to git.

Perhaps the bootstrapper should ensure that the git user is configured and has access to the private repos and else skip them.

This does not really break anything. But it makes it seem like things went wrong with the installation and provides no clues as to how to fix it (for people who are new to the system)

**Comment by MatthijsBurgh** [comment]
This is not related to git configuration, but generating a ssh key and adding that one to your GitHub account. This isn't a tue-env issue, but more related to our specific use of it.

**Comment by PetervDooren** [comment]
Yeah it does give the warning of lacking access rights. So that is probably clear enough
