### ISSUE TITLE
Installer: apt-get: one unfound package causes nothing to be installed

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue-env#550]
While making a new installation I found that when a single package is not found, the entire list of apt-get packages will not be installed. If however we do an `apt-get install package` for every package it will take a lot of time.
However the system as it is right now will be very vulnerable to a single error in a single target.

> Going to run the following command:
> 
> sudo apt-get install --assume-yes -q  geany google-chrome-stable sublime-text-installer meld terminator libqt5core5a libqt5gui5 qtbase5-dev libqt5widgets5 ros-melodic-moveit-ros-visualization ros-melodic-joint-state-publisher ros-melodic-moveit-ros-move-group ros-melodic-moveit-simple-controller-manager ros-melodic-robot-state-publisher ros-melodic-moveit-planners-ompl ros-melodic-xacro htop net-tools ssh nmap avahi-dnsconfd git-extras git-gui gitk ccache ros-melodic-depth-image-proc python-markdown ros-melodic-viz ros-melodic-rviz ros-melodic-rosauth ros-melodic-rosnode ros-melodic-rosgraph ros-melodic-rosservice ros-melodic-rostopic python-psutil festival sox python-packaging ros-melodic-rqt-gui-py ros-melodic-rqt-gui ros-melodic-diagnostic-updater python-opencv python-catkin-lint python-docopt libzbar-dev ros-melodic-std-srvs ros-melodic-gazebo-msgs ros-melodic-slam-gmapping ros-melodic-geometry ros-melodic-rostest ros-melodic-map-msgs ros-melodic-dynamic-reconfigure ros-melodic-pluginlib ros-melodic-laser-geometry ros-melodic-tf2-sensor-msgs ros-melodic-tf2 ros-melodic-tf2-geometry-msgs ros-melodic-tf2-ros ros-melodic-diagnostics ros-melodic-moveit-ros-planning-interface ros-melodic-moveit-msgs ros-melodic-actionlib-msgs ros-melodic-diagnostic-msgs ros-melodic-interactive-markers ros-melodic-rospy ros-melodic-control-msgs ros-melodic-actionlib ros-melodic-nav-msgs ros-melodic-image-transport ros-melodic-common-msgs ros-melodic-stereo-msgs ros-melodic-rosbag ros-melodic-class-loader ros-melodic-urdf ros-melodic-rosconsole liburdfdom-headers-dev libyaml-cpp-dev libeigen3-dev ros-melodic-message-filters ros-melodic-pcl-ros ros-melodic-image-geometry ros-melodic-roscpp ros-melodic-tf libassimp-dev ros-melodic-shape-msgs libsdformat6-dev libpcl-dev libtinyxml-dev ros-melodic-cmake-modules ros-melodic-std-msgs ros-melodic-geometry-msgs ros-melodic-sensor-msgs ros-melodic-tf-conversions ros-melodic-cv-bridge ros-melodic-visualization-msgs
> 
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package sublime-text-installer
> 
> Error while installing target 'APT-GET':
> 
>     An error occurred while installing system packages.
> 

In this particular case it was the package sublime-text-installer which could not be found.

**Comment by PetervDooren** [comment]
@MatthijsBurgh and @ar13pit, I consider you guys the tue-env experts. What is your opinion on this?

**Comment by ar13pit** [comment]
@PetervDooren Your observation is correct. There are a couple of solutions that lie between installing one or all packages. 
One is to install packages in batches. That would allow most of the packages to install anyway. 
The other is to search for the existence of a package in apt-cache.

**Comment by Timple** [comment]
Fail-hard or fail-early are actually concepts ;-)

Why try a lot of stuff if you already know the end-result is not going to be met? What do you achieve, lots of build-time wasted, no satisfactory endresult.

**Comment by PetervDooren** [comment]
I think the fail badly vs fail well concept applies here. We don't need all packages perce. You need a set of them to do robot-things but nothing will break if geany is not installed. And if a package is skipped here it will be tried again the next time a tue-get update is called. 
For the 95% of packages that can be installed: Why wait with installing these packages if you know they need to be installed to get to the end-result.
That is my view on the situation but it might be a matter of taste

**Comment by MatthijsBurgh** [comment]
I think the current fail method is correct. You wanted to install a target with many dependencies, so if stuff fails. You can try to install (some of) it's dependencies separately.

So that `tue-get list-installed` only shows successfully installed targets. Though I think that failure of apt/pip/snap doesn't prevent that right now. So that requires a fix.

The current method of installing the apt/pip/snap in the end in a batch, makes it impossible to find out to which target the missing package belongs to. You will need to search the log for where it gets added.

We could do a test with disabling the batch install. The time to generate the docker image should be a good indicator. We could split apt/pip/snap over multiple branches, to see what the impact is for each installer.
