### ISSUE TITLE
Indigo support

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue-env#6]
This issue tracks which packages already compile at indigo.

- [x] action_server
- [x] amigo_demo
- [x] amigo_description
- [x] amigo_diagnostics
- [x] amigo_hardware
- [x] amigo_head_ref
- [x] amigo_launch_files
- [x] amigo_machine_files
- [x] amigo_msgs
- [x] amigo_navigation_local_3d
- [x] amigo_parameters
- [x] amigo_ref_interpolator
- [x] ann2
- [x] armadillo_matrix
- [x] base_local_planner
- [x] cb_base_navigation
- [x] cb_planner_msgs_srvs
- [x] challenge_basic_functionalities
- [x] challenge_cocktail_party
- [x] challenge_demo
- [x] challenge_final
- [x] challenge_follow_me
- [x] challenge_gpsr
- [x] challenge_logger
- [x] challenge_manipulation
- [x] challenge_person_recognition
- [x] challenge_rips
- [x] code_profiler
- [x] costmap_2d
- [x] depth_map_self_filter
- [x] depth_map_to_point_cloud
- [x] dragonfly_speech_recognition
- [x] dwa_local_planner
- [x] ed
- [x] ed_gui_server
- [x] ed_object_models
- [x] ed_perception
- [x] fast_simulator
- [x] fast_simulator_data
- [x] geolib2
- [x] head_ref
- [x] head_ref_ed_client
- [x] nav_core
- [x] node_alive
- [x] obj_in_gripper
- [x] pein_msgs
- [x] pein_srvs
- [x] perception_srvs
- [x] problib
- [x] psi
- [x] rgbd
- [x] robot_skills
- [x] robot_skill_server
- [x] robot_smach_states
- [x] rtt_control_components
- [x] rtt_control_msgs
- [x] rtt_tue_msgs
- [x] scan_to_cloud_converter
- [x] scl_filters
- [x] soem
- [x] soem_beckhoff_drivers
- [x] soem_master
- [x] speech_interpreter
- [x] state_viewer
- [x] teleop
- [x] text_to_speech
- [x] tf_server
- [x] tue_astar_planner_3d
- [x] tue_carrot_planner
- [x] tue_computer_monitor
- [x] tue_config
- [x] tue_costmap_msgs
- [x] tue_ethercat_drivers
- [x] tue_filesystem
- [x] tue_knowledge
- [x] tue_manipulation
- [x] tue_map_3d
- [x] tue_maps
- [x] tue_mobile_ui
- [x] tue_move_base_3d
- [x] tue_move_base_msgs
- [x] tue_msgs
- [x] tue_nav_core_3d
- [x] tue_pocketsphinx
- [x] tue_reasoner_core
- [x] tue_recorder
- [x] tue_robocup
- [x] tue_serialization
- [x] tue_teleop_keyboard
- [x] virtual_cam
- [x] vocabulary_tree
- [x] voxel_grid
- [x] wire_core
- [x] wire_interface
- [x] wire_msgs
- [x] wire_state_estimators
- [x] wire_viz

**Comment by Rayman** [comment]
From 66% (67 of 101) to 75% (65 of 87)

**Comment by Timple** [comment]
Included amigo_hardware and rtt packages

**Comment by Rayman** [comment]
On Ubuntu 14.04 everything compiles from `tue-dev` except `tue_pocketsphinx` and `state_viewer`. The first one is obsolete so we should remove it from the targets. What is `state_viewer` used for?

**Comment by svddries** [comment]
Ohh, state_viewer is OLD. No idea what it is doing there. Can be removed from the targets!
