### ISSUE TITLE
No license defined

### ISSUE THREAD

**Issue by akaihola** [tue-robotics/tue-env#603]
There's no license definition in this repository. For that reason, it's not possible to re-use any of the code in other repositories.

We encountered this in practice with @MatthijsBurgh when he suggested to use [ci/commit-range/action.yml](https://github.com/tue-robotics/tue-env/blob/master/ci/commit-range/action.yml) in the [Darker](https://github.com/akaihola/darker) project (see akaihola/darker#260). I can't copy that GitHub action definition to the Darker repository since there's no license.

**Comment by MatthijsBurgh** [comment]
#604 should fix this
