### ISSUE TITLE
Add our RoboCup GIT mirror as a separate remote instead of overwriting origin

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue-env#79]
The tue-set-github-originand thereabouts scripts replace the ```origin```-remote: from github to out server.

This is precisely the opposite what you should do in git: it is much nicer to simply add our server as a new remote, e.g. robocup-server. 

Each branch has a default remote, usually origin. With 
```bash
git branch --set-upstream-to master robocup-server/master
```
(from http://stackoverflow.com/questions/3599412/git-how-to-specify-a-default-remote-push-to-branch) 

we can change between the two without thinking while still being able to push to github when needed.

**Comment by MatthijsBurgh** [comment]
Is it also an idea to really clone all the repos on the server? Instead of the current mirror process. Because for some reason the current setup did not allow me to push from the server. Therefore I had to check on my pc, which didn't contain all the repos.

**Comment by LoyVanBeek** [comment]
The server is also just a clone (it is a bare clone, without a working directory), as is your computer. Master is locked on GitHub, regardless of which clone pushes to it. So that is why you cannot push from the server to github.

**Comment by MatthijsBurgh** [comment]
No, it was not even connecting to GitHub. It is definitely not related to the masters being locked. But it is something to research to smooth the process after Japan.

**Comment by LoyVanBeek** [comment]
Probably, the server was also still configured with a static IP and thus not able to get on the TU/e network

**Comment by MatthijsBurgh** [comment]
Loy, I am not stupid. I already solved that problem. It was clearly a git issue

**Comment by LoyVanBeek** [comment]
OK :-). We'll take a look on Tuesday

**Comment by MatthijsBurgh** [comment]
Fixed by #267 and #269
