### ISSUE TITLE
Add udev rules to SERGIO1 target

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env#80]

**Comment by MatthijsBurgh** [comment]
Example: https://github.com/tue-robotics/tue-env/tree/master/installer/targets/pico

**Comment by Rayman** [comment]
Is this still an issue?

**Comment by MatthijsBurgh** [comment]
Yep. Not much work, just not looked into yet.

**Comment by MatthijsBurgh** [comment]
AMIGO fixed by #202
